### PR TITLE
Added systemd init support

### PR DESCRIPTION
**Pull request by Stopka**
Hi, added systemd init support to your mkinicpio script. I added second mkinicpio hook called sd-tpm2, which adds two systemd services to initramfs and a script that works as adapter to your init hooks.

### CODE REVIEW

**Comment by baudlord** [comment]
Hey @electrickite any chance of getting this merged and into the AUR package?
I've been running it manually and it works wonder with systemd initrd. :)

**Comment by electrickite** [comment]
Overall this looks good. I will merge when I get a chance to fully review.

**Comment by electrickite** [comment]
Looks good overall. A few tweaks to make and then will push to AUR.

**Comment by electrickite** [comment]
@Stopka @baudlord The latest AUR package should contain the systemd integration. Please let me know if there are any issues. Note that the default inclusion of `/etc/tpm2-encrypt/{key.{pub,priv}` has been removed, but the files can be added back in using `/mkinitcpio.conf` if needed.

**Comment by Stopka** [comment]
Thanks, It seems working. I installed the v1.6 package from AUR, added keys to mkinitcpio.conf and root drive is still unsealing properly using tpm2.

**Pull request merged**
